# Generated by Django 4.1.3 on 2022-11-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='Qanigelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Ta`lim yo`nalishi',
                'verbose_name_plural': 'Ta`lim yo`nalishlari',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], default='I', max_length=4)),
                ('kurs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('book_name', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('book_author', models.CharField(max_length=255, verbose_name='Kitob Avtorlari')),
                ('year', models.DateField(null=True, verbose_name='Nashr yili')),
                ('isbn', models.CharField(max_length=15, null=True, verbose_name='ISBN yoki ISSN')),
                ('printing_office', models.CharField(max_length=100, null=True, verbose_name='Bosmaxona')),
                ('science', models.CharField(max_length=100, null=True, verbose_name='Fan nomi')),
                ('teacher', models.CharField(max_length=100, null=True, verbose_name='O`qituvchi ismi, familyasi va sharifi')),
                ('book_number', models.IntegerField(null=True, verbose_name='Kibobxonadagi kitoblar soni')),
                ('elektron_bool', models.BooleanField(default=False, null=True, verbose_name='Elektron shakilda mavjudligi')),
                ('book_url_file', models.URLField(null=True, verbose_name='Kitob URL adresi')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.booklanguage', verbose_name='Kitob tili')),
                ('yunalish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.qanigelik', verbose_name='Yunalish')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
