# Generated by Django 4.1.3 on 2022-11-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kibobxonadagi kitoblar soni'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_url_file',
            field=models.URLField(blank=True, null=True, verbose_name='Kitob URL adresi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='elektron_bool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Elektron shakilda mavjudligi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ISBN yoki ISSN'),
        ),
        migrations.AlterField(
            model_name='books',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.booklanguage', verbose_name='Kitob tili'),
        ),
        migrations.AlterField(
            model_name='books',
            name='printing_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bosmaxona'),
        ),
        migrations.AlterField(
            model_name='books',
            name='science',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='O`qituvchi ismi, familyasi va sharifi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Nashr yili'),
        ),
        migrations.AlterField(
            model_name='books',
            name='yunalish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.qanigelik', verbose_name='Yunalish'),
        ),
    ]
