# Generated by Django 4.1.6 on 2023-02-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_lang_alter_books_yunalish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaf_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='kafedra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.kafedra', verbose_name='Kafedra'),
        ),
    ]
