# Generated by Django 4.1.6 on 2023-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_booklanguage_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanigelik',
            name='yonalish',
            field=models.CharField(max_length=200),
        ),
    ]
